"""Curated portfolio projects. Edit links and summaries here."""

PROJECTS = [
    dict(slug="glados-assitente-ti", name="Glados · Assistente de TI", category="IA & Automação", summary="Assistente de TI que conecta conversas, IA e sistemas internos para encaminhar solicitações e automatizar consultas.", problem="Centralizar solicitações operacionais e reduzir etapas manuais no atendimento.", stack=["n8n", "OpenAI", "GLPI", "Oracle", "Redis", "WhatsApp"], filters=["RPA", "IA", "GLPI", "Integrações"], featured=True, repo="https://github.com/Sipauba/glados-assitente-ti", symbol="✳"),
    dict(slug="notifica-status-gerador-energia", name="Monitor de energia e gerador", category="IoT & Monitoramento", summary="Monitoramento com ESP32 do fornecimento de energia, funcionamento do gerador e temperatura, com alertas remotos.", problem="Dar visibilidade rápida a mudanças no estado da energia e do gerador.", stack=["ESP32", "C++", "Arduino", "Telegram API"], filters=["IoT", "Integrações"], featured=True, repo="https://github.com/Sipauba/notifica-status-gerador-energia", symbol="⌁"),
    dict(slug="bot-cobranca", name="Bot de cobrança", category="RPA & Financeiro", summary="Fluxo que consulta títulos financeiros, prepara mensagens de cobrança e organiza notificações via WhatsApp.", problem="Agilizar consultas e comunicação em uma rotina financeira recorrente.", stack=["n8n", "Oracle", "PostgreSQL", "WhatsApp API"], filters=["RPA", "Integrações"], featured=True, repo="https://github.com/Sipauba/bot-cobranca", symbol="↗"),
    dict(slug="integra-glpi-ti-e-rh-admissao", name="Integração RH → TI · Admissão", category="Integrações & RH", summary="Automação que transforma solicitações de admissão do RH em demandas técnicas de criação de acessos no GLPI.", problem="Conectar RH e TI para iniciar a preparação de acessos sem redigitação.", stack=["n8n", "GLPI", "OpenAI", "REST API"], filters=["RPA", "IA", "GLPI", "Integrações"], repo="https://github.com/Sipauba/integra-glpi-ti-e-rh-admissao", symbol="↳"),
    dict(slug="integra-glpi-ti-e-rh-demissao", name="Integração RH → TI · Desligamento", category="Integrações & RH", summary="Fluxo de desligamento que converte solicitações do RH em tarefas técnicas para remoção de acessos.", problem="Organizar o repasse de desligamentos e apoiar a revogação de acessos.", stack=["n8n", "GLPI", "OpenAI", "REST API"], filters=["RPA", "IA", "GLPI", "Integrações"], repo="https://github.com/Sipauba/integra-glpi-ti-e-rh-demissao", symbol="↳"),
    dict(slug="notifica-solicitacao-de-validacao-glpi", name="Validações pendentes no GLPI", category="RPA & Service Desk", summary="Notificações via WhatsApp para responsáveis por validações de chamados pendentes no GLPI.", problem="Evitar que solicitações aguardem validação sem visibilidade.", stack=["n8n", "GLPI", "MySQL", "WhatsApp API"], filters=["RPA", "GLPI", "Integrações"], repo="https://github.com/Sipauba/notifica-solicitacao-de-validacao-glpi", symbol="◉"),
    dict(slug="notifica-chamados-vencendo", name="Alertas de SLA no GLPI", category="RPA & Service Desk", summary="Acompanhamento de chamados próximos do vencimento com alertas preventivos via WhatsApp.", problem="Antecipar a atenção da equipe a chamados com prazo de SLA próximo.", stack=["n8n", "GLPI", "MySQL", "WhatsApp API"], filters=["RPA", "GLPI", "Integrações"], repo="https://github.com/Sipauba/notifica-chamados-vencendo", symbol="◷"),
    dict(slug="glados-auto-atendimento-n8n", name="Glados · Autoatendimento", category="IA & Service Desk", summary="Fluxo de autoatendimento em n8n para orientar e encaminhar solicitações de TI.", problem="Oferecer uma primeira resposta estruturada a demandas recorrentes.", stack=["n8n", "GLPI", "WhatsApp", "IA"], filters=["RPA", "IA", "GLPI", "Integrações"], repo="https://github.com/Sipauba/glados-auto-atendimento-n8n", symbol="✳"),
    dict(slug="pinga_ni_mim", name="Pinga ni mim", category="Automação & Comunicação", summary="Projeto de automação de comunicação para rotinas operacionais.", problem="Facilitar o envio e acompanhamento de comunicações em processos recorrentes.", stack=["Automação", "Integrações"], filters=["RPA", "Integrações"], repo="https://github.com/Sipauba/pinga_ni_mim", symbol="↗"),
    dict(slug="relatorio-setor-compras", name="Follow up de compras", category="Dados & Compras", summary="Aplicativo desktop que consulta pedidos do WinThor e exporta um relatório de acompanhamento em Excel.", problem="Substituir a montagem manual de relatórios de pedidos e entregas.", stack=["Python", "Oracle", "Tkinter", "Pandas", "Excel"], filters=["RPA", "Integrações"], repo="https://github.com/Sipauba/relatorio-setor-compras", symbol="▥"),
]
